### ISSUE TITLE
Newb shader link broken

### ISSUE THREAD

**Issue by sinaSPOGames** [DominoKorean/Render-dragon-shader-list#13]
it uses discord links and since 2023 discord changed how links do stream and they have an expiration date
they dont work anymore and just says this content is not available anymore

**Comment by DominoKorean** [comment]
I have tested all the Discord links related to Newb X Legacy, and they all work fine. Can you leave a screenshot or link for which one didn't work for you?

**Comment by sinaSPOGames** [comment]
when I open them in browser it says this content is no longer available in a 52 sized text that's all

**Comment by sinaSPOGames** [comment]
discord has been changed the way file pinks work they have expire date now
using Dropbox links would do better

**Comment by DominoKorean** [comment]
https://github.com/DominoKorean/Render-dragon-shader-list/commit/fbbd0d5e473cdc9f9da4ea0205ce0b1bd1fa0703
I have fixed all the non-working Discord links.
The list of RenderDragon shaders does not involve re-uploading files directly, but rather, it involves retrieving links to shader files officially provided on the Discord server.
Therefore, I cannot upload the files to Dropbox myself.

**Comment by sinaSPOGames** [comment]
> https://github.com/DominoKorean/Render-dragon-shader-list/commit/fbbd0d5e473cdc9f9da4ea0205ce0b1bd1fa0703
> I have fixed all the non-working Discord links.
> The list of RenderDragon shaders does not involve re-uploading files directly, but rather, it involves retrieving links to shader files officially provided on the Discord server.
> Therefore, I cannot upload the files to Dropbox myself.

but you will eventually need to update them again since discord links now expire after couple of weeks

**Comment by sinaSPOGames** [comment]
I'm in their discord server if you want I can tell newb's owner to upload those into Dropbox or Google drive as well for this page

**Comment by DominoKorean** [comment]
Some shaders in Discord servers like YSSBE, NewbX, and Getmoon are considering including files directly in the repository. I will try to contact those shaders developers.

**Comment by atashi764** [comment]
> Some shaders in Discord servers like YSSBE, NewbX, and Getmoon are considering including files directly in the repository. I will try to contact those shaders developers.

Tell them to make their own repos and provide you links instead. Otherwise it would be really hard for you to collect all the files yourself and managing them.

**Comment by sinaSPOGames** [comment]
alright i told them about this
time will tell us what will happen
ill let yall know if they upload any of newb shaders into non expireable links (or repos xd)

**Comment by DominoKorean** [comment]
> > Some shaders in Discord servers like YSSBE, NewbX, and Getmoon are considering including files directly in the repository. I will try to contact those shaders developers.
> 
> Tell them to make their own repos and provide you links instead. Otherwise it would be really hard for you to collect all the files yourself and managing them.

NewbX shaders have already been stored at
https://github.com/DominoKorean/Render-dragon-shader-list/tree/main/files/newbX
and connected there. For the other shaders, I'm currently modifying them to continuously allow downloads only for the latest versions.
I will ask Endermanyk and Haruu again about the repository.
Currently, except for YSS and YSS SE,
you can normally download the latest versions of Getmoon and NewbX.

**Comment by sinaSPOGames** [comment]
thats awesome
for future updates just remember avoid using Discord links
instead Github or OpenDrive direct raw links will do the job the most
(literally an openworld sandbox game's world editor maps had to update over 1430 textures due discord's weird decisions btw)

**Comment by DominoKorean** [comment]
I have replaced the links for all files of the latest version of shader packs connected through Discord with other links, even if not for all versions. For YSS, the shaders are now fetched from yss.minecraft.pe. For NewbX, they are fetched from https://github.com/DominoKorean/Render-dragon-shader-list/tree/main/files/newbX and NewbX's GitHub releases. For GetMoon, the official releases are already fetched from Mediafire.
