### ISSUE TITLE
Add draco-injector

### ISSUE THREAD

**Issue by mcbegamerxx954** [DominoKorean/Render-dragon-shader-list#18]
Its a injector that can patch normal minecraft apk's and also allows you to clone them so that you can install them alongside the original one.
(The reason i named it that was because injector name is too generic + renderdragon)
https://github.com/mcbegamerxx954/draco-injector

**Comment by mcbegamerxx954** [comment]
#19 does this

**Comment by DominoKorean** [comment]
I have merged your pull request.
