### ISSUE TITLE
Please update newb patched app

### ISSUE THREAD

**Issue by mcbegamerxx954** [DominoKorean/Render-dragon-shader-list#26]
The newb patchedapp has a very simple bug where redirector would not scan external storage, causing issues for some people using external storage, they released a bugfix for that now

**Comment by DominoKorean** [comment]
https://github.com/DominoKorean/Render-dragon-shader-list/commit/a54ba88a33d3f9ad44a879bc36c9c28a2f52cc44
I have added the new APK with the bug fixed to the list.
