### ISSUE TITLE
YSS RD Shader link broken.

### ISSUE THREAD

**Issue by Mistyre9309** [DominoKorean/Render-dragon-shader-list#27]
I am trying to download the YSS RD v1.9.8 BETA 1, but it just goes to a discord file attachment and says This content is no longer available. As said in Issue 13, they have an expiration date (and they already expired). So please add new links, or use a different shortener (for example, Mediafire)

**Comment by DominoKorean** [comment]
I have updated the latest version file of the YSS Shader with the link to the YSS webpage. Now, all shader packs that are redirected through Discord are working correctly with the latest version.
