### ISSUE TITLE
problem in Minecraft Patch 1.21.0.03 

### ISSUE THREAD

**Issue by S24Ultra** [DominoKorean/Render-dragon-shader-list#31]
The minecraft patch doesn't install on my phone due to an error, and it ends up not being compatible, I'm trying to install it to have the patch and as normal, without needing to enter Minecraft Beta to get the shaders  
![Screenshot_20240622_134220_SAI](https://github.com/DominoKorean/Render-dragon-shader-list/assets/173566171/bcdb46fc-c9ee-4acf-ba7f-efb4c970f529)

Screenshot translation: Application not installed The package does not contain native code compatible with the CPU of this device

**Comment by atashi764** [comment]
@S24Ultra it's because your phone only supports 64 bit applications.

the solution to this is, download arm64 apk from yss. 

https://www.mediafire.com/file/mgpqw1voqnz9lik/1.21.0.03__arm64_patched.apk/file

**Comment by DominoKorean** [comment]
I do not understand the reason for raising this issue. I have already noted at the top that the patched app must distinguish between 32-bit and 64-bit, and that the appropriate APK should be installed for each specification.
![Screenshot_20240623_173938_Chrome](https://github.com/DominoKorean/Render-dragon-shader-list/assets/110039366/74f3eafe-07c6-4f55-b88c-9679fac825ab)

**Comment by DominoKorean** [comment]
Please read the text at the top of the [Patched App doc](https://github.com/DominoKorean/Render-dragon-shader-list/blob/main/patchedapp.md). Depending on whether your phone is 32-bit or 64-bit, you need to install the corresponding APK. If arm32 is included in the APK name, it is for 32-bit; if arm64 is included, it is for 64-bit.

**Comment by Nurasyil13** [comment]
1.21.0.03_arm64 patched.apk

**Comment by Nurasyil13** [comment]
patched.apk

**Comment by Banhh1711** [comment]
Tại sao tôi không thể tải các minecraft trong đây tôi muốn tải bản minecraft patch 1.21.0.03

**Comment by alijim348-ctrl** [comment]
Vhcjvpj

**Comment by alijim348-ctrl** [comment]
.l bkvjvjv
