### ISSUE TITLE
Not installing 

### ISSUE THREAD

**Issue by Hellothere1234627284yehnsndnsnwnd** [DominoKorean/Render-dragon-shader-list#32]
On one phone it is downloading but on other it isn't, I donno what is the problem other minecraft appa are downloading and running but the patched one aren't downloading no matter what I do
![Screenshot_2024-06-23-11-31-23-365_com google android packageinstaller](https://github.com/DominoKorean/Render-dragon-shader-list/assets/107072543/73819670-cde9-438c-93be-e3fb3e05bd1f)

**Comment by DominoKorean** [comment]
Check if your phone is 32-bit. If it is 64-bit, look for solutions on the internet. The 'App not installed' message can appear in various situations. It is likely caused by external factors rather than the app itself being corrupted.

**Comment by Hellothere1234627284yehnsndnsnwnd** [comment]
Thanku it worked
