### ISSUE TITLE
The promlem with texture

### ISSUE THREAD

**Issue by Finnish9** [DominoKorean/Render-dragon-shader-list#33]
![Screenshot_20240628-154947](https://github.com/DominoKorean/Render-dragon-shader-list/assets/174109473/f771ef8e-296f-4341-9750-fa54850f0ca3)

**Comment by DominoKorean** [comment]
Significant changes have been made to existing materials since version 1.20.80.
Please check if the shader you intend to use is supported by versions 1.20.80 and above.

**Comment by atashi764** [comment]
@Finnish9 here is a collection of shaders that support 1.20.80+

https://github.com/atashi764/v2-rd-shader-list

**Comment by DominoKorean** [comment]
> @Finnish9 here is a collection of shaders that support 1.20.80+
> 
> https://github.com/atashi764/v2-rd-shader-list

Do not re-upload the shader pack without the developer's permission. Please delete the Google Drive link.

**Comment by atashi764** [comment]
> Do not re-upload the shader pack without the developer's permission. Please delete the Google Drive link.

I didn't upload it. Another guy who discovered manifestVersion V2 thingy made the drive link. (found from draco chat)

**Comment by DominoKorean** [comment]
> > Do not re-upload the shader pack without the developer's permission. Please delete the Google Drive link.
> 
> I didn't upload it. Another guy who discovered manifestVersion V2 thingy made the drive link. (found from draco chat)

Just because you didn't upload it doesn't mean you can share it in the repository README. Permission from the shader pack developer is still required. Also, the pack contains shader files that do not support version 1.20.80.

**Comment by atashi764** [comment]
i see, i will take it down soon

**Comment by mcbegamerxx954** [comment]
> @Finnish9 here is a collection of shaders that support 1.20.80+
> 
> https://github.com/atashi764/v2-rd-shader-list

I have a tool that can port shader packs to 1.20.80+, it has some bugs and issues but it works fine with most packs, also draco patch can do this automatically
