### ISSUE TITLE
Minecraft 1.21.0.03

### ISSUE THREAD

**Issue by Itztop** [DominoKorean/Render-dragon-shader-list#35]
I cant log my xbox account into minecraft, pls help me.

**Comment by DominoKorean** [comment]
Are you using an iPhone?

**Comment by Itztop** [comment]
> Are you using an iPhone?

No it's android phone

**Comment by DominoKorean** [comment]
When using RenderDragon shaders, you may often be unable to join multiplayer servers or log into your Xbox account. Please contact the [YSS Group](https://discord.com/invite/MN6Kdta6uA), who created the patched app.
