### ISSUE TITLE
Move older shader versions to new .md 

### ISSUE THREAD

**Issue by atashi764** [DominoKorean/Render-dragon-shader-list#37]
Most people will download only the latest version and not care about older versions.

You may want to move all the older version links to another .md

and also leave a link to the same #title of the new.md

by doing this, the readme.md will become easier to read and write. currently, it's easy to get lost in dozens of older links.

**Comment by DominoKorean** [comment]
It doesn't seem necessary to separate the documentation for the old and new versions of the shaders. (From a management perspective, separating the documents would make it harder to manage.)
Instead, I will consider moving the shaders that support the current changed materials to the top and organizing the previous versions using the `<details>` tag to allow for collapsible sections.

**Comment by atashi764** [comment]
makes sense. i went through the readme today and i felt that links to older version makes the md look messy. 

i mean lets assume a shader has 100 older versions, then you will have to add 100 extra lines in the same md.

instead what i wanted is something like this 

> README.md
> oldversions.md

in README it would look like this:

> ### Newb X Legacy
> (shields.io badges>)
> [v15.49](https://github.com/devendrn/newb-x-mcbe/releases/tag/v15-dev) (beta)
> [Android](https://github.com/devendrn/newb-x-mcbe/releases/download/v15-dev/newb-x-legacy-15.49-android.mcpack)
> [iOS](https://github.com/devendrn/newb-x-mcbe/releases/download/v15-dev/newb-x-legacy-15.49-ios.zip)
> [Windows](https://github.com/devendrn/newb-x-mcbe/releases/download/v15-dev/newb-x-legacy-15.49-windows.mcpack)
>
> Links to older and beta versions: https://github.com/DominoKorean/Render-dragon-shader-list/blob/main/oldversions.md#newb-x-legacy

and in oldversions.md
> ### Newb X Legacy
> (shields.io badges)
> [v15.49](https://github.com/devendrn/newb-x-mcbe/releases/tag/v15-dev) (beta)
> [Android](https://github.com/devendrn/newb-x-mcbe/releases/download/v15-dev/newb-x-legacy-15.49-android.mcpack)
> [iOS](https://github.com/devendrn/newb-x-mcbe/releases/download/v15-dev/newb-x-legacy-15.49-ios.zip)
> [Windows](https://github.com/devendrn/newb-x-mcbe/releases/download/v15-dev/newb-x-legacy-15.49-windows.mcpack)
>
> [v15.48](https://github.com/devendrn/newb-x-mcbe/releases/tag/v15-dev) (beta)
> [Android](https://github.com/devendrn/newb-x-mcbe/releases/download/v15-dev/newb-x-legacy-15.48-android.mcpack)
> [iOS](https://github.com/devendrn/newb-x-mcbe/releases/download/v15-dev/newb-x-legacy-15.48-ios.zip)
> [Windows](https://github.com/devendrn/newb-x-mcbe/releases/download/v15-dev/newb-x-legacy-15.48-windows.mcpack)
> `100 other versions`

i suggested this because:
1. most people will not download older version anyways
2. having more links in one file will degrade page loading performance over time
3. from user perspective the page wouldn't look that bad. but from editor perspective it just lowers clear visibility of everything

**Comment by DominoKorean** [comment]
Although I am in a fast internet environment with 5G, I am not sure if having many links or lines significantly slows down the loading speed of the document. If this truly causes a noticeable lag, it is certainly worth considering.
However, sometimes the shader updates to a new version and stops working, which means I occasionally need to refer to older versions. It is very inconvenient to have to search for these materials each time.
Given that the RenderDragon shader list currently experiences an average of 40,000 daily traffic, it is important to consider the various situations of different users.

From a management perspective, although these aspects can make pull requests challenging, this is not a concern for the majority of users.

As long as the document loading speed is not slowed down, I do not currently plan to change this aspect.
