### ISSUE TITLE
Problems with "Render Dragon" in version 1.21

### ISSUE THREAD

**Issue by Mayczine** [DominoKorean/Render-dragon-shader-list#42]
Now with the Minecraft 1.20+ update, we need to use an option called "Render Dragon" which allows the use of more detailed and realistic shaders, but in this Minecraft 1.21 modification The option to activate Render Dragon does not appear, nor does the one at the end of the "Video" part of the game settings

**Comment by atashi764** [comment]
You're probably talking about deferred rendering. It requires both compatible device and a texture pack which supports PBR.

**Comment by DominoKorean** [comment]
If you are referring to deferred rendering, it is indeed a new feature of RenderDragon but it is not a shader. The deferred rendering preview can be checked in the preview version by applying the PBR resource pack, enabling the RenderDragon deferred preview in the experimental features of the map, and then checking the bottom of the settings/video settings.
