### ISSUE TITLE
A Small Question

### ISSUE THREAD

**Issue by musclepisya** [DominoKorean/Render-dragon-shader-list#48]
Is it possible to install a patched version on Windows 10 edition? If there is such a thing at all, or so far only for apk files?

**Comment by atashi764** [comment]
funny how patch has made people think shaders only work on patch but nothing else.

it's only for armeabi-v7a and arm-v8a based phones. 

here the term 'patched' simply means being able to load shaders from resource packs. if you want that capability on windows 10 edition use betterRenderDragon 1.4.3 here: https://github.com/DominoKorean/Render-dragon-shader-list?tab=readme-ov-file#betterrenderdragon

it may give false virus warnings as every thing that does some kind of memory injection is considered malicious.

**Comment by DominoKorean** [comment]
Patch literally means that it has been modified, in other words, it has been modded. If you want to use [materialbinloader](https://github.com/ddf8196/MaterialBinLoader) to load shaders through a resource pack, you can find it yourself and follow the guide for installation. Additionally, there is [betterrenderdragon](https://github.com/DominoKorean/Render-dragon-shader-list?tab=readme-ov-file#betterrenderdragon), which is already easy to use.
