### ISSUE TITLE
YSS RD LINK NOT WORKING/MISSING

### ISSUE THREAD

**Issue by Bjorntam** [DominoKorean/Render-dragon-shader-list#50]
![image_2024-07-27_005605830](https://github.com/user-attachments/assets/cd441761-a325-4f29-96f9-6dba044da461)

github link is not working also the main website said page not found, cute creeper tho

![image_2024-07-27_005641209](https://github.com/user-attachments/assets/e2d39419-46f0-4dc1-b2a8-49344af4eb15)

**Comment by DominoKorean** [comment]
It seems that all pages except for Home and About Us are down. Please download from the Discord server through the menu.

**Comment by atashi764** [comment]
just in case anyone needs discord server link: discord.gg/yss

**Comment by Jeppapa** [comment]
Also just in case you don't have discord: https://yss.minecraft.pe/en/YSS_SE/

**Comment by DominoKorean** [comment]
> Also just in case you don't have discord: https://yss.minecraft.pe/en/YSS_SE/

When this issue arose, the download page of the YSS site was temporarily down.

**Comment by DominoKorean** [comment]
Since the YSS site has been restored, I will close the issue.
