### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by RandomasterIdiot** [DominoKorean/Render-dragon-shader-list#51]
Not a issue with the Minecraft patched itself but just a suggestion, maybe you should put out a different way to download the file, mediafire is kinda annoying and limits the download speed alot, it takes hours for me to get to download things there. I just think it would be better if we could download it a different way that didn't limit the download speed and doesn't make it take longer than it should on purpose

**Comment by RandomasterIdiot** [comment]
![Screenshot_20240728-174413_Chrome](https://github.com/user-attachments/assets/112ffe2a-8042-44c3-9e0e-8d1a4b5f0569)
According to google, I would have to wait 4 whole hours to download the game. Which is kinda insane, isn't it? And also kinda upsetting when your in a hurry to play the game already but you can't because of this. And before you say "oh, it's just your internet." Not really man, any other random websites would download it in less than 25 minutes but with mediafire it's like this. Really weird.

**Comment by DominoKorean** [comment]
Medifire may have slower download speeds compared to other sites, but it shouldn't take more than an hour to download. This suggests that the problem is more likely with your internet speed. If you want to suggest changing the download platform, please contact the developer distributing the pack with a clear alternative in mind.

**Comment by RandomasterIdiot** [comment]
I think it might just be a problem with mobile because in other websites I could download things that are 1gb in size but it never took atleast an hour to download, it only happens with mediafire. Maybe you guys could distribute the apk through mega?

**Comment by DominoKorean** [comment]
At least on my phone and other people's phones, that issue does not occur, which means it is a problem with your device. Also, I am not the one uploading the patched app on MediaFire. For that matter, please contact the developer of the patched app.

**Comment by RandomasterIdiot** [comment]
Who is the one who uploaded it?

**Comment by DominoKorean** [comment]
https://discord.gg/yss

**Comment by RandomasterIdiot** [comment]
"the invite link is invalid or has expired."

**Comment by DominoKorean** [comment]
https://discord.com/invite/MN6Kdta6uA

**Comment by RandomasterIdiot** [comment]
Thanks I'll join
