### ISSUE TITLE
X86 or .exe version???

### ISSUE THREAD

**Issue by ThomasMarchetti** [DominoKorean/Render-dragon-shader-list#58]

**Comment by faizul726** [comment]
what you're talking about?

if it's betterRenderDragon then go for the .zip in releases

**Comment by DominoKorean** [comment]
For support regarding 86x, please ask your questions on [Betterrenderdragon](https://github.com/ddf8196/BetterRenderDragon/issues).  
There is no exe file available. Whether it's a bat file or an exe file, the result will be the same.
