### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by miqumi** [DominoKorean/Render-dragon-shader-list#9]
Ok not gonna let your effort down but honestly the current readme looks ass.
It's a pain to go through each and every screenshot link one by one,
especially when you are sending the repo link to an untrained friend.
If instead of something like
> ### Newb X
> ![](https://img.shields.io/badge/Android-black?style=flat-square&logo=android)
> ![](https://img.shields.io/badge/iOS_&_iPadOS-0A84E1?style=flat-square&logo=Apple)
> ![](https://img.shields.io/badge/Windows-0078D6?style=flat-square&logo=Windows)
> ![](https://img.shields.io/badge/MaterialBinLoader-6F8761?style=flat-square)  
> [![](https://img.shields.io/badge/Screen_Shots-click-white?style=social-square)](screenshots/Newb%20X)  
> https://devendrn.github.io/newb-shader  

could be
> [![image](https://github.com/DominoKorean/Render-dragon-shader-list/assets/80510430/7cd21088-04cf-423f-8b57-24565a7ec700)](https://devendrn.github.io/newb-shader)
\(its clickable\)

This was just an example of NO quality so uhh yeah could be better 
\(I can do it if I get time this week :D \)

**Comment by DominoKorean** [comment]
Yes, I was also contemplating the same issue. I refrained from using the method of including large screenshots as it increases the length of the list and disrupts the flow. While I would prefer to build a webpage using Github Pages, I lack the skills and knowledge to create one. Therefore, I am considering adding elongated banner-like images. For links that require joining Discord servers like YSSBE or where viewing screenshots from the link is not possible, I'm thinking of keeping the screenshot files but making them collapsible within the README.md, rather than redirecting to another document.

**Comment by miqumi** [comment]
> Yes, I was also contemplating the same issue. I refrained from using the method of including large screenshots as it increases the length of the list and disrupts the flow. While I would prefer to build a webpage using Github Pages, I lack the skills and knowledge to create one. Therefore, I am considering adding elongated banner-like images. For links that require joining Discord servers like YSSBE or where viewing screenshots from the link is not possible, I'm thinking of keeping the screenshot files but making them collapsible within the README.md, rather than redirecting to another document.

I like that idea, and I appreciate that you've already finished adding a banner for most of the shaders;
and while I think it's good the way it is right now, the newb shader banner doesn't display the shader in its full glory,

we can do something more like the image on the original readme:
**The Original**:
[![original](https://github.com/devendrn/newb-x-mcbe/raw/main/docs/screenshots.jpg)](https://github.com/devendrn/newb-x-mcbe)
**Example of what we can do**:
[![our_take](https://github.com/DominoKorean/Render-dragon-shader-list/assets/80510430/3871baa7-d536-437c-924a-c6c01a6ba472)](https://github.com/devendrn/newb-x-mcbe)


###### THIS IS A VERY AMATEUR ATTEMPT!!!! Please don't take my words negatively ;-;

If you DO wish to update the banner, you can make a much better one than I did; just remember to bring as many aspects of the shader together into the image without it feeling crammed 👍

###### You can make it more simplistic; I made it a bit colorful in my example because I like flashy colors :D

**Comment by DominoKorean** [comment]
In many platforms, only one representative image of a post is shown, and one must click on the post to view the various images associated with it. RDShaderList used a banner that is wide horizontally and narrow vertically, so as not to disrupt the flow and to avoid increasing the length of the scroll.
Therefore, if multiple images are included in the banner, it may appear cluttered and distracting, especially on small mobile screens. Of course, this is just my opinion, so I will ask the community for their thoughts and decide accordingly.

**Comment by miqumi** [comment]
> In many platforms, only one representative image of a post is shown, and one must click on the post to view the various images associated with it. RDShaderList used a banner that is wide horizontally and narrow vertically, so as not to disrupt the flow and to avoid increasing the length of the scroll. Therefore, if multiple images are included in the banner, it may appear cluttered and distracting, especially on small mobile screens. Of course, this is just my opinion, so I will ask the community for their thoughts and decide accordingly.

I didn't mean to show multiple images, I meant to say use one banner that is a combination of multiple images, 
I totally respect your opinions; this was just a clarification and any change is upto your will
